/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { ChatRoomModelJobApplication } from './chatRoomModelJobApplication';
import type { MessageModel } from './messageModel';

export interface ChatRoomModel {
  id: string;
  job_application_id: string;
  /** @nullable */
  jobApplication: ChatRoomModelJobApplication;
  /** @nullable */
  messages: MessageModel[] | null;
  /** 안읽은 메시지 수 */
  unreadCount: number;
  createdAt: string;
}
