/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

export type ChatControllerFindMessagesParams = {
  /**
   * 조회할 메시지 수
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * 커서 (메시지 UUID)
   */
  cursor?: string;
};
