/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { PetDto } from './petDto';
import type { CreateJobDtoPriceType } from './createJobDtoPriceType';

export interface CreateJobDto {
  /** 시작 일시 (ISO 8601) */
  start_time: string;
  /** 종료 일시 (ISO 8601) */
  end_time: string;
  /**
   * 공고 내용
   * @minLength 5
   * @maxLength 500
   */
  activity: string;
  /** 반려동물 목록 (1~10마리) */
  pets: PetDto[];
  /** POST /photos/upload 으로 사전 업로드한 공고 사진 ID 목록 */
  photo_ids?: string[];
  /** 공고 위치 주소 */
  address?: string;
  /** 위도 (WGS84) */
  latitude?: number;
  /** 경도 (WGS84) */
  longitude?: number;
  /**
   * 가격 (원 단위)
   * @minimum 0
   */
  price?: number;
  /** 가격 단위 (hourly: 시간당 / daily: 일당) */
  price_type?: CreateJobDtoPriceType;
}
