/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

export interface CreateReviewDto {
  /**
   * 별점 (1~5)
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /** 리뷰 텍스트 (선택) */
  comment?: string;
}
