/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { CreateUserDtoRolesItem } from './createUserDtoRolesItem';

export interface CreateUserDto {
  /** 이메일 주소 */
  email: string;
  /**
   * @minLength 2
   * @maxLength 50
   */
  full_name: string;
  /**
   * 비밀번호 (최소 8자)
   * @minLength 8
   */
  password: string;
  /** 역할 목록 (PetOwner, PetSitter, Admin) */
  roles: CreateUserDtoRolesItem[];
}
