/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

/**
 * 가격 단위 (hourly: 시간당 / daily: 일당)
 */
export type CreateJobDtoPriceType =
  (typeof CreateJobDtoPriceType)[keyof typeof CreateJobDtoPriceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateJobDtoPriceType = {
  hourly: 'hourly',
  daily: 'daily',
} as const;
