/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

export type JobApplicationModelStatus =
  (typeof JobApplicationModelStatus)[keyof typeof JobApplicationModelStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobApplicationModelStatus = {
  applying: 'applying',
  approved: 'approved',
  rejected: 'rejected',
} as const;
