/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { JobApplicationModelStatus } from './jobApplicationModelStatus';
import type { JobApplicationModelUser } from './jobApplicationModelUser';
import type { JobApplicationModelJob } from './jobApplicationModelJob';

export interface JobApplicationModel {
  id: string;
  status: JobApplicationModelStatus;
  user_id: string;
  job_id: string;
  /** @nullable */
  user: JobApplicationModelUser;
  /** @nullable */
  job: JobApplicationModelJob;
  createdAt: string;
  updatedAt: string;
}
