/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

/**
 * @nullable
 */
export type JobModelPriceType = (typeof JobModelPriceType)[keyof typeof JobModelPriceType] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobModelPriceType = {
  hourly: 'hourly',
  daily: 'daily',
} as const;
