/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { JobModelAddress } from './jobModelAddress';
import type { JobModelLatitude } from './jobModelLatitude';
import type { JobModelLongitude } from './jobModelLongitude';
import type { JobModelPrice } from './jobModelPrice';
import type { JobModelPriceType } from './jobModelPriceType';
import type { PetModel } from './petModel';
import type { PhotoModel } from './photoModel';

export interface JobModel {
  id: string;
  creator_user_id: string;
  start_time: string;
  end_time: string;
  activity: string;
  /** @nullable */
  address: JobModelAddress;
  /** @nullable */
  latitude: JobModelLatitude;
  /** @nullable */
  longitude: JobModelLongitude;
  /** @nullable */
  price: JobModelPrice;
  /** @nullable */
  price_type: JobModelPriceType;
  pets: PetModel[];
  /** 공고에 첨부된 사진 목록 */
  photos: PhotoModel[];
  createdAt: string;
  updatedAt: string;
}
