/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

export type JobsControllerFindAllParams = {
  /**
   * 이 날짜 이전에 시작하는 공고
   */
  start_time_before?: string;
  /**
   * 이 날짜 이후에 시작하는 공고
   */
  start_time_after?: string;
  /**
   * 이 날짜 이전에 종료하는 공고
   */
  end_time_before?: string;
  /**
   * 이 날짜 이후에 종료하는 공고
   */
  end_time_after?: string;
  /**
   * 공고 내용 키워드 검색
   */
  activity?: string;
  /**
   * 이 나이 이하의 반려동물 공고 (pets[age_below])
   * @minimum 1
   */
  'pets[age_below]'?: number;
  /**
   * 이 나이 이상의 반려동물 공고 (pets[age_above])
   * @minimum 1
   */
  'pets[age_above]'?: number;
  /**
   * 종류 필터. 여러 개는 쉼표 구분 (예: Cat,Dog) (pets[species])
   */
  'pets[species]'?: string;
  /**
   * 페이지당 항목 수
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * 다음 페이지 커서 (응답의 cursor 값)
   */
  cursor?: string;
  /**
   * 정렬 기준 (예: start_time:asc, end_time:desc)
   */
  sort?: string;
  /**
   * 최소 가격 필터 (이상)
   * @minimum 0
   */
  min_price?: number;
  /**
   * 최대 가격 필터 (이하)
   * @minimum 0
   */
  max_price?: number;
};
