/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

export interface LoginDto {
  /** 이메일 */
  email: string;
  /** 비밀번호 */
  password: string;
}
