/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { MessageModelSender } from './messageModelSender';

export interface MessageModel {
  id: string;
  content: string;
  sender_id: string;
  chat_room_id: string;
  /** @nullable */
  sender: MessageModelSender;
  createdAt: string;
}
