/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

export interface PageInfo {
  /** 다음 페이지 존재 여부 */
  hasNextPage: boolean;
  /**
   * 다음 페이지 커서
   * @nullable
   */
  endCursor: string | null;
}
