/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { JobModel } from './jobModel';
import type { PageInfo } from './pageInfo';

export interface PaginatedJobs {
  /** 구인공고 목록 */
  items: JobModel[];
  /** 페이지 정보 */
  pageInfo: PageInfo;
}
