/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { MessageModel } from './messageModel';
import type { PaginatedMessagesNextCursor } from './paginatedMessagesNextCursor';

export interface PaginatedMessages {
  /** 메시지 목록 */
  messages: MessageModel[];
  /**
   * 다음 페이지 커서
   * @nullable
   */
  nextCursor: PaginatedMessagesNextCursor;
}
