/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { PetDtoSpecies } from './petDtoSpecies';

export interface PetDto {
  /**
   * 반려동물 이름
   * @minLength 2
   * @maxLength 20
   */
  name: string;
  /**
   * 나이
   * @minimum 1
   * @maximum 100
   */
  age: number;
  /** 종류 (Cat / Dog) */
  species: PetDtoSpecies;
  /** 품종 */
  breed: string;
  /** 크기 (소형/중형/대형 등) */
  size?: string;
  /** POST /photos/upload 으로 사전 업로드한 Photo ID 목록 */
  photo_ids?: string[];
}
