/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

/**
 * 종류 (Cat / Dog)
 */
export type PetDtoSpecies = (typeof PetDtoSpecies)[keyof typeof PetDtoSpecies];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetDtoSpecies = {
  Cat: 'Cat',
  Dog: 'Dog',
} as const;
