/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { PetModelSpecies } from './petModelSpecies';
import type { PetModelSize } from './petModelSize';
import type { PhotoModel } from './photoModel';

export interface PetModel {
  id: string;
  name: string;
  age: number;
  species: PetModelSpecies;
  breed: string;
  /** @nullable */
  size: PetModelSize;
  job_id: string;
  /** 반려동물에 첨부된 사진 목록 */
  photos: PhotoModel[];
  createdAt: string;
  updatedAt: string;
}
