/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { PhotoModelUserId } from './photoModelUserId';
import type { PhotoModelJobId } from './photoModelJobId';
import type { PhotoModelPetId } from './photoModelPetId';

export interface PhotoModel {
  id: string;
  url: string;
  file_name: string;
  original_name: string;
  mime_type: string;
  size: number;
  uploader_id: string;
  /** @nullable */
  user_id: PhotoModelUserId;
  /** @nullable */
  job_id: PhotoModelJobId;
  /** @nullable */
  pet_id: PhotoModelPetId;
  createdAt: string;
}
