/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { ReviewModelComment } from './reviewModelComment';

export interface ReviewModel {
  id: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  /** @nullable */
  comment: ReviewModelComment;
  reviewer_id: string;
  reviewee_id: string;
  job_id: string;
  createdAt: string;
  updatedAt: string;
}
