/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

export interface ToggleFavoriteDto {
  /** 즐겨찾기에 추가/제거할 공고 ID */
  job_id: string;
}
