/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

export interface ToggleFavoriteResult {
  /** 추가됐으면 true, 제거됐으면 false */
  added: boolean;
}
