/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

/**
 * 지원 상태 (applying / approved / rejected)
 */
export type UpdateJobApplicationDtoStatus =
  (typeof UpdateJobApplicationDtoStatus)[keyof typeof UpdateJobApplicationDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateJobApplicationDtoStatus = {
  applying: 'applying',
  approved: 'approved',
  rejected: 'rejected',
} as const;
