/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

export type UpdateUserDtoRolesItem =
  (typeof UpdateUserDtoRolesItem)[keyof typeof UpdateUserDtoRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserDtoRolesItem = {
  PetOwner: 'PetOwner',
  PetSitter: 'PetSitter',
  Admin: 'Admin',
} as const;
