/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { UpdateJobApplicationDtoStatus } from './updateJobApplicationDtoStatus';

export interface UpdateJobApplicationDto {
  /** 지원 상태 (applying / approved / rejected) */
  status: UpdateJobApplicationDtoStatus;
}
