/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { PetDto } from './petDto';
import type { UpdateJobDtoPriceType } from './updateJobDtoPriceType';

export interface UpdateJobDto {
  /** 시작 일시 */
  start_time?: string;
  /** 종료 일시 */
  end_time?: string;
  /**
   * @minLength 5
   * @maxLength 500
   */
  activity?: string;
  /** 반려동물 목록 교체 */
  pets?: PetDto[];
  address?: string;
  latitude?: number;
  longitude?: number;
  /**
   * 가격 (원 단위)
   * @minimum 0
   */
  price?: number;
  price_type?: UpdateJobDtoPriceType;
}
