/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { UpdateUserDtoRolesItem } from './updateUserDtoRolesItem';

export interface UpdateUserDto {
  /** 변경할 이메일 */
  email?: string;
  /** @maxLength 20 */
  full_name?: string;
  /**
   * @minLength 8
   * @maxLength 20
   */
  password?: string;
  roles?: UpdateUserDtoRolesItem[];
}
