/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */

export type UserModelRolesItem = (typeof UserModelRolesItem)[keyof typeof UserModelRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserModelRolesItem = {
  PetOwner: 'PetOwner',
  PetSitter: 'PetSitter',
  Admin: 'Admin',
} as const;
