/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * PetSitter API
 * PetSitter REST API 문서 — Code First 자동 생성
 * OpenAPI spec version: 0.1
 */
import type { UserModelRolesItem } from './userModelRolesItem';
import type { PhotoModel } from './photoModel';

export interface UserModel {
  id: string;
  email: string;
  full_name: string;
  roles: UserModelRolesItem[];
  /** 프로필 사진 목록 */
  photos: PhotoModel[];
  createdAt: string;
  updatedAt: string;
}
